# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-06 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_aid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkout.Address'),
        ),
    ]
