# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-08 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20171207_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.Address'),
        ),
    ]
