# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-08 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_auto_20171204_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='postcode',
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='PA', help_text='Use the state abbreviation, such as PA', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='zipCode',
            field=models.CharField(default='15217', max_length=5),
            preserve_default=False,
        ),
    ]
